FS: 22050                              # in Hz
DATAPOINT_DUR: 10                      # in seconds
ENV_FS: 100                            # in Hz
LOWPASS_CUTOFF: 10                     # in Hz
PATH_TO_FILES: 'data/separated_vocals' # path where the data lives
DESREO:
  RND_INIT:
    ENABLE: True
    F0_INIT_CENT: 4
TRAIN:
  ENABLE: True
SOLVER:
  PATIENCE_LIM: 20
  LR: 0.001
DATA_LOADER:
  NUM_WORKERS: 12
